<?php

namespace app\TecnologiesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TecnologyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TecnologyRepository extends EntityRepository
{
}
